apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000 # Replace with the port your web application is listening on
  selector:
    app.kubernetes.io/name: web
